/**
 * S3 asset URLs (generated by scripts/upload-assets.mjs).
 * Re-run that script to refresh after adding/changing assets.
 */
import urls from "@/generated-asset-urls.json";

const byKey = (urls as { byKey: Record<string, string> }).byKey;

export const logo = byKey.logo;
export const footerBackground = byKey.footerBackground;
export const heroBackground = byKey.heroBackground;
export const heroProduct = byKey.heroProduct;
export const avatar = byKey.avatar;
export const shopBackground = byKey.shopBackground;
export const aboutUsBackground = byKey.aboutUsBackground;
export const instagramBackground = byKey.instagramBackground;
export const avatarMale = byKey.avatarMale;
export const avatarFemale = byKey.avatarFemale;
export const testimonialCardBg = byKey.testimonialCardBg;
export const product1 = byKey.product1;
export const product2 = byKey.product2;
export const product3 = byKey.product3;
export const product4 = byKey.product4;
export const elevate1 = byKey.elevate1;
export const elevate2 = byKey.elevate2;
export const elevate3 = byKey.elevate3;
export const elevate4 = byKey.elevate4;
export const categoryTote = byKey.categoryTote;
export const categorySling = byKey.categorySling;
export const categoryClutches = byKey.categoryClutches;
export const categoryMini = byKey.categoryMini;
