/**
 * S3 asset URLs (generated by scripts/upload-assets.mjs).
 * Re-run that script to refresh after adding/changing assets.
 *
 * All images are loaded from the CDN; we do not bundle
 * any large static PNGs from `src/assets` here.
 */
import urls from "@/generated-asset-urls.json";

const byKey = (urls as { byKey: Record<string, string> }).byKey;

export const logo = byKey.logo;
export const footerBackground = byKey.footerBackground;
export const heroBackground = byKey.heroBackground;
export const heroProduct = byKey.heroProduct;
export const avatar = byKey.avatar;
export const shopBackground = byKey.shopBackground;
export const aboutUsBackground = byKey.aboutUsBackground;
export const instagramBackground = byKey.instagramBackground;
export const avatarMale = byKey.avatarMale;
export const avatarFemale = byKey.avatarFemale;
export const testimonialCardBg = byKey.testimonialCardBg;
export const product1 = byKey.product1;
export const product2 = byKey.product2;
export const product3 = byKey.product3;
export const product4 = byKey.product4;

// Elevate section: use only the four explicitly provided CDN URLs
export const elevate1 =
  "https://vedify-backend-dev.s3.eu-north-1.amazonaws.com/uploads/uploads/1773644573097_a9a5cce2d97005cea8a7b06346aa88db.png";
export const elevate2 =
  "https://vedify-backend-dev.s3.eu-north-1.amazonaws.com/uploads/uploads/1773644586784_1304f8f05413ab5869849921d089709c.png";
export const elevate3 =
  "https://vedify-backend-dev.s3.eu-north-1.amazonaws.com/uploads/uploads/1773644629664_fb8abdd29d2eb50998e3e14d0b4cb177.png";
export const elevate4 =
  "https://vedify-backend-dev.s3.eu-north-1.amazonaws.com/uploads/uploads/1773644644078_Gemini_Generated_Image_cakdzwcakdzwcakd__1_.png";

export const categoryTote = byKey.categoryTote;
export const categorySling = byKey.categorySling;
export const categoryClutches = byKey.categoryClutches;
export const categoryMini = byKey.categoryMini;
