/**
 * S3 asset URLs (generated by scripts/upload-assets.mjs).
 * Re-run that script to refresh after adding/changing assets.
 */
import urls from "@/generated-asset-urls.json";
import elevate1Img from "@/assets/fb8abdd29d2eb50998e3e14d0b4cb177.png";
import elevate2Img from "@/assets/Gemini_Generated_Image_cakdzwcakdzwcakd (1).png";
import elevate3Img from "@/assets/a9a5cce2d97005cea8a7b06346aa88db.png";
import elevate4Img from "@/assets/1304f8f05413ab5869849921d089709c.png";

const byKey = (urls as { byKey: Record<string, string> }).byKey;

export const logo = byKey.logo;
export const footerBackground = byKey.footerBackground;
export const heroBackground = byKey.heroBackground;
export const heroProduct = byKey.heroProduct;
export const avatar = byKey.avatar;
export const shopBackground = byKey.shopBackground;
export const aboutUsBackground = byKey.aboutUsBackground;
export const instagramBackground = byKey.instagramBackground;
export const avatarMale = byKey.avatarMale;
export const avatarFemale = byKey.avatarFemale;
export const testimonialCardBg = byKey.testimonialCardBg;
export const product1 = byKey.product1;
export const product2 = byKey.product2;
export const product3 = byKey.product3;
export const product4 = byKey.product4;

// Elevate section: use the four static local assets provided
export const elevate2 = elevate1Img;
export const elevate4 = elevate2Img;
export const elevate1 = elevate3Img;
export const elevate3 = elevate4Img;

export const categoryTote = byKey.categoryTote;
export const categorySling = byKey.categorySling;
export const categoryClutches = byKey.categoryClutches;
export const categoryMini = byKey.categoryMini;
